### ISSUE TITLE
Comments do not match the ascii values

### ISSUE THREAD

**Issue by ShiraNagen** [wooorm/is-hexadecimal#7]
In the index file, you have a mistake in the comments
![Screen Shot 2022-03-16 at 9 25 32](https://user-images.githubusercontent.com/85055696/158537978-26d3a097-bd1b-438d-9e6a-574c9fe6e2ff.png)

it should be: 
```  
    (code >= 97 /* a */ && code <= 102) /* f */ ||
    (code >= 65 /* A */ && code <= 70) /* F */ ||
    (code >= 48 /* 0 */ && code <= 57) /* 9 */

**Comment by wooorm** [comment]
Hah, whoops, you’re right. Want to work on a PR to fix it?

**Comment by ShiraNagen** [comment]
Cool, I'll open a PR

**Comment by wooorm** [comment]
Thanks, fixed!
